# Generated by Django 3.1.3 on 2021-01-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='health_points',
            field=models.SmallIntegerField(default=100),
        ),
    ]
