# Generated by Django 3.1.3 on 2021-01-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0002_enemy_health_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='id',
        ),
        migrations.AlterField(
            model_name='enemy',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
