# Generated by Django 3.1.3 on 2021-01-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210111_0003'),
        ('enemies', '0003_auto_20210108_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='user',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='username',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
